version: "3.7"
services:
  db:
    container_name: dv-local-mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "local"
      # So you don't have to use root, but you can if you like
      MYSQL_USER: "user"
      # You can use whatever password you like
      MYSQL_PASSWORD: "passXXXX"
      # Password for root access
      MYSQL_ROOT_PASSWORD: "passYYYY"
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3306:3306"
    expose:
      # Opens port 3306 on the container
      - "3306"
      # Where our data will be persisted
    volumes:
      - v-local-mysql:/var/lib/mysql
  rabbit:
    container_name: dv-local-rabbit
    image: 3.10.5-management-alpine
    restart: always
    container_name: dv-local-rabbit
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=twin2port
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - v-local-rabbit:/var/lib/rabbitmq
  email:
    container_name: dv-local-email
    image: mailhog/mailhog:v1.0.1
    restart: always
    ports:
     - "1025:1025" #SMTP
     - "8025:8025" #HTTP
  ldap:
    container_name: dv-local-ldap
    image: bitnami/openldap:latest
    restart: always
    environment:
      LDAP_ROOT: "o=myu.ed"
      LDAP_PASSWORD: "test-password"
      LDAP_CUSTOM_LDIF_DIR: "/custom"
    ports:
      - "1389:1389"
    expose:
      - "1389"
    volumes:
      # Where our ldif files are stored
      - $LOCAL_LDAP_DIR/custom:/custom
      - $LOCAL_LDAP_DIR/schema:/schema

volumes:
  v-local-rabbit:
  v-local-mysql:

